# Generated by Django 4.2.13 on 2024-07-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoPage',
        ),
    ]
