# Generated by Django 4.2.13 on 2024-05-31 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntityInfo',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='date',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
