# Generated by Django 4.2.13 on 2024-07-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_delete_videopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='tariff_role',
            field=models.CharField(max_length=255, null=True, verbose_name='Для какой роли этот тариф'),
        ),
    ]
