# Generated by Django 4.2.13 on 2024-05-31 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('info', '0002_delete_entityinfo_remove_blogpage_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('id_billing', models.IntegerField(verbose_name='ID биллинга')),
                ('name', models.CharField(max_length=255, verbose_name='Имя тарифа')),
                ('description', models.CharField(max_length=1024, verbose_name='Описание тарифа')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='TablePage',
        ),
    ]
