# Generated by Django 4.2.13 on 2024-05-31 02:41

from django.db import migrations
import info.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_tariff_rename_blogpage_tablepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablepage',
            options={'verbose_name': 'Таблица по тарифам', 'verbose_name_plural': 'Таблица по тарифам'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterField(
            model_name='tablepage',
            name='table',
            field=wagtail.fields.StreamField([('table', info.models.TableBlockCustom())], blank=True, null=True, use_json_field=True),
        ),
    ]
