# Generated by Django 4.2.13 on 2024-07-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('info', '0003_tariff_tariff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivotTableTariff',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Сводная таблица по тарифам',
                'verbose_name_plural': 'Сводная таблица по тарифам',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tariff_role',
            field=models.CharField(blank=True, choices=[('role_1', 'First role'), ('role_2', 'Second role'), ('role_3', 'Third role')], max_length=255, null=True, verbose_name='Для какой роли этот тариф'),
        ),
    ]
