# Generated by Django 4.2.13 on 2024-07-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='MediaPage',
        ),
        migrations.AlterModelOptions(
            name='mediapage',
            options={'verbose_name': 'Страница с медиа', 'verbose_name_plural': 'Страница с медиа'},
        ),
    ]
