# Generated by Django 4.2.13 on 2024-07-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('videos', '0002_rename_blogpage_mediapage_alter_mediapage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapage',
            name='media_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailmedia.media', verbose_name='Ссылка на media'),
        ),
    ]
